## Multi-Class Classification

take clustered data, classify

In [21]:
# check installed version
import pycaret
import pandas as pd
pycaret.__version__

'3.0.4'

In [22]:
load_clustered = pd.read_csv('clustered/clustered_meanshift _2023-09-04 14:59:41.csv')
load_clustered

,Unnamed: 0,precursor_buy_cap_pct_change,precursor_ask_cap_pct_change,precursor_bid_vol_pct_change,precursor_ask_vol_pct_change,change.1,change,sum_change,surge_area,Cluster
0,0,-0.000618,-0.000017,-0.000210,-0.002384,-0.000533,0.505364,0.505364,0.505364,Cluster 2
1,1,-0.002358,-0.000002,-0.000818,-0.000333,0.000135,0.000670,0.000670,0.000670,Cluster 0
2,2,0.004750,-0.000036,0.001573,-0.004835,-0.000233,0.001273,0.001808,0.003615,Cluster 0
3,3,-0.000987,0.000002,-0.000398,0.000062,-0.000502,0.000873,0.002114,0.004229,Cluster 0
4,4,0.001531,0.000010,0.000334,0.001094,-0.000768,0.001305,0.001305,0.001305,Cluster 0
...,...,...,...,...,...,...,...,...,...,...
5538,5630,0.000251,0.003062,0.000103,0.014462,-0.000796,0.001598,0.003393,0.006786,Cluster 0
5539,5631,0.000555,0.000699,0.000168,0.003437,-0.000398,0.001297,0.001297,0.001297,Cluster 0
5540,5633,0.004809,0.000779,0.001181,0.003685,0.000399,0.000599,0.000599,0.000599,Cluster 0
5541,5634,-0.000989,-0.000484,-0.000248,-0.002320,0.000000,0.000898,0.000898,0.000898,Cluster 0
5542,5635,0.006274,-0.001249,0.001518,-0.005973,0.000000,0.000699,0.000699,0.000699,Cluster 0

In [23]:
# clustered.drop(['group', 'time', 's_MP', 'change', 'type', 'length', 'sum_change', 'surge_area' ] , axis=1, inplace=True) 
print(load_clustered.columns)

Index(['Unnamed: 0', 'precursor_buy_cap_pct_change',
       'precursor_ask_cap_pct_change', 'precursor_bid_vol_pct_change',
       'precursor_ask_vol_pct_change', 'change.1', 'change', 'sum_change',
       'surge_area', 'Cluster'],
      dtype='object')

In [24]:
#eliminate surge columns, 'change', 'sum_change','surge_area',
keepable = ['precursor_buy_cap_pct_change',
       'precursor_ask_cap_pct_change', 
        'precursor_bid_vol_pct_change',
       'precursor_ask_vol_pct_change', 
        'change.1', 
        'Cluster']
clustered = load_clustered[keepable]

In [25]:
#setup 
from pycaret.classification import *
s = setup(clustered, target = 'Cluster', session_id = 42)

In [26]:
from pycaret.classification import ClassificationExperiment
exp = ClassificationExperiment()

In [27]:
type(exp)

pycaret.classification.oop.ClassificationExperiment

In [28]:
exp.setup(clustered, target = 'Cluster', session_id = 42)

In [ ]:
best = compare_models()

,,
,,
Initiated,. . . . . . . . . . . . . . . . . .,17:22:03
Status,. . . . . . . . . . . . . . . . . .,Fitting 10 Folds
Estimator,. . . . . . . . . . . . . . . . . .,Light Gradient Boosting Machine

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

In [ ]:
plot_model(best, plot = 'confusion_matrix')

In [ ]:
# plot_model(best, plot = 'auc')

In [ ]:
# plot_model(best, plot = 'efficiency')
# #

In [ ]:
evaluate_model(best)

In [ ]:
holdout_pred = predict_model(best)

In [ ]:
holdout_pred.head()

### loading a model

In [ ]:
# check installed version
import pycaret
import pandas as pd
pycaret.__version__

In [ ]:
# functional API
# loaded_model = load_model('iforest_pipeline')
# print(loaded_model)

# OOP API
# loaded_model = s.load_model('kmeans_pipeline')
# print(loaded_model)